from nanovllm.config import Config
from nanovllm.engine.sequence import Sequence, SequenceStatus
from nanovllm.engine.scheduler import Scheduler, SchedulerOutput


class AsyncScheduler(Scheduler):
    """Scheduler for vLLM-V1-style async scheduling.

    Uses *output placeholders* to optimistically reserve KV-cache slots
    for tokens being generated by in-flight GPU work (vLLM's "future
    token ids").  Placeholders are only added for **decode** batches —
    prefill-containing steps run after the pipeline is drained, so no
    placeholders are needed.  Finished sequences may be scheduled one
    extra (wasted) step before the CPU notices — their release is
    deferred by the engine.
    """

    def __init__(self, config: Config):
        super().__init__(config)
        self.num_sampled_tokens_per_step = 1

    # ------------------------------------------------------------------
    # Schedule
    # ------------------------------------------------------------------

    def schedule(self) -> SchedulerOutput:
        output = super().schedule()

        # Only add placeholders for pure-decode batches.  Mixed batches
        # (prefill + decode) are executed synchronously in the engine so
        # no placeholders are needed.
        if not output.is_prefill:
            for seq in output.scheduled_seqs:
                seq.num_output_placeholders += self.num_sampled_tokens_per_step

        return output

    # ------------------------------------------------------------------
    # Output processing
    # ------------------------------------------------------------------

    def update_from_output(
        self,
        seqs: list[Sequence],
        token_ids: list[int],
        is_prefill: bool,
    ) -> list[Sequence]:
        """Apply one step's sampled tokens; returns sequences that just
        finished.  The CALLER owns releasing their KV blocks / state slots
        / GPU rows: with async scheduling a finished sequence may still be
        referenced by newer in-flight steps, so release() must be deferred
        until the last of them completes (see LLMEngine).
        """
        finished: list[Sequence] = []
        for seq, token_id in zip(seqs, token_ids):
            if seq.is_finished:
                # Optimistic scheduling ran this sequence one extra step
                # after its actual finish — the row is simply discarded.
                continue
            if seq.is_prefill:
                num_scheduled = seq.num_scheduled_tokens
                self.block_manager.hash_blocks(seq, num_scheduled)
                seq.num_cached_tokens += num_scheduled
                seq.num_scheduled_tokens = 0
            else:
                self.block_manager.hash_blocks(seq, self.num_sampled_tokens_per_step)
                # Only consume a placeholder if one was actually reserved
                # (the sync path for mixed batches doesn't add them).
                if seq.num_output_placeholders > 0:
                    seq.num_output_placeholders -= self.num_sampled_tokens_per_step
                seq.num_cached_tokens += self.num_sampled_tokens_per_step
                # Leave num_scheduled_tokens for the next async step.

            # Chunked prefill: don't append token until all prompt tokens
            # are processed.
            if seq.is_prefill and seq.num_cached_tokens < seq.num_tokens:
                continue

            seq.append_token(token_id)

            if (
                (not seq.ignore_eos and token_id == self.eos)
                or seq.num_completion_tokens == seq.max_tokens
            ):
                seq.status = SequenceStatus.FINISHED
                if seq in self.running:
                    self.running.remove(seq)
                finished.append(seq)
        return finished

    def release(self, seq: Sequence):
        """Free a finished sequence's KV blocks and state slot (deferred
        until no in-flight step references it)."""
        self.block_manager.deallocate(seq)
        self._free_state_slot(seq)

    def postprocess(self, seqs: list[Sequence], token_ids: list[int], is_prefill: bool):
        for seq in self.update_from_output(seqs, token_ids, is_prefill):
            self.release(seq)

    # ------------------------------------------------------------------
    # Preemption
    # ------------------------------------------------------------------

    def preempt(self, seq: Sequence):
        seq.status = SequenceStatus.WAITING
        seq.is_prefill = True
        seq.num_output_placeholders = 0
        self.block_manager.deallocate(seq)
        self.waiting.appendleft(seq)
