from nanovllm.config import Config
from nanovllm.engine.sequence import Sequence, SequenceStatus
from nanovllm.engine.scheduler import Scheduler, SchedulerOutput


class AsyncScheduler(Scheduler):
    """Async scheduler that runs one step ahead of GPU execution.

    Uses *output placeholders* to optimistically reserve KV-cache slots
    for tokens being generated by in-flight GPU work.  Placeholders are
    only added for **decode** sequences — prefill chunks are always
    synchronous.
    """

    def __init__(self, config: Config):
        super().__init__(config)
        self.num_sampled_tokens_per_step = 1

    # ------------------------------------------------------------------
    # Schedule
    # ------------------------------------------------------------------

    def schedule(self) -> SchedulerOutput:
        output = super().schedule()

        # Only add placeholders for pure-decode batches.  Mixed batches
        # (prefill + decode) are executed synchronously in the engine so
        # no placeholders are needed.
        if not output.is_prefill:
            for seq in output.scheduled_seqs:
                seq.num_output_placeholders += self.num_sampled_tokens_per_step

        return output

    # ------------------------------------------------------------------
    # Output processing
    # ------------------------------------------------------------------

    def update_from_output(
        self,
        seqs: list[Sequence],
        token_ids: list[int],
        is_prefill: bool,
    ):
        for seq, token_id in zip(seqs, token_ids):
            if seq.is_prefill:
                num_scheduled = seq.num_scheduled_tokens
                self.block_manager.hash_blocks(seq, num_scheduled)
                seq.num_cached_tokens += num_scheduled
                seq.num_scheduled_tokens = 0
            else:
                self.block_manager.hash_blocks(seq, self.num_sampled_tokens_per_step)
                # Only consume a placeholder if one was actually reserved
                # (the sync path for mixed batches doesn't add them).
                if seq.num_output_placeholders > 0:
                    seq.num_output_placeholders -= self.num_sampled_tokens_per_step
                seq.num_cached_tokens += self.num_sampled_tokens_per_step
                # Leave num_scheduled_tokens for the next async step.

            # Chunked prefill: don't append token until all prompt tokens
            # are processed.
            if seq.is_prefill and seq.num_cached_tokens < seq.num_tokens:
                continue

            seq.append_token(token_id)

            if (
                (not seq.ignore_eos and token_id == self.eos)
                or seq.num_completion_tokens == seq.max_tokens
            ):
                seq.status = SequenceStatus.FINISHED
                self.block_manager.deallocate(seq)
                self._free_state_slot(seq)
                self.running.remove(seq)

    def postprocess(self, seqs: list[Sequence], token_ids: list[int], is_prefill: bool):
        self.update_from_output(seqs, token_ids, is_prefill)

    # ------------------------------------------------------------------
    # Preemption
    # ------------------------------------------------------------------

    def preempt(self, seq: Sequence):
        seq.status = SequenceStatus.WAITING
        seq.is_prefill = True
        seq.num_output_placeholders = 0
        self.block_manager.deallocate(seq)
        self.waiting.appendleft(seq)
